### ISSUE TITLE
Microservice Tutorial

### ISSUE THREAD

**Issue by zchoy001** [mankenavenkatesh/ProgrammingLanguages#1]
Hi, I am trying microservice tutorial on medium.com with your source code.

I get 

{
    "timestamp": "2019-01-07T09:32:58.222+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "No message available",
    "path": "/auth"
}
when  i enter 

{
	"username": "admin",
	"password": "12345"
}
to localhost:8762/auth

**Comment by mankenavenkatesh** [comment]
I tried it again. It's working for me. Run the services in the following order
eureka, config, auth, image, gallery, gateway. 


I have added postman collection for the request. Try with this.
https://github.com/mankenavenkatesh/ProgrammingLanguages/tree/Java/microservices-springboot/postman-collection

**Comment by zchoy001** [comment]
Hi,

I tried running the services in the stated order and ran your postman collection file.

I am still getting unauthorised 401 for both requests.. 

Any idea what may be causing the issue?? Please see my attached exported results, thanks..

[microservices.postman_test_run.zip](https://github.com/mankenavenkatesh/ProgrammingLanguages/files/2732990/microservices.postman_test_run.zip)

**Comment by mankenavenkatesh** [comment]
We can have a call to check this. Let me know when do you want to have a call?

**Comment by zchoy001** [comment]
Hi,

Thanks. That would be helpful.

I'm available today. Let me know when is a good time for you?  How should
we do this ? Through Skype ?

**Comment by mankenavenkatesh** [comment]
Please ping me over gmail or facebook. i will send you meeting link.
facebook - https://www.facebook.com/mankena.venkatesh
gmail - mankenavenkatesh@gmail.com

**Comment by mankenavenkatesh** [comment]
Using Java8 resolved the issue. closing the issue.

**Comment by mankenavenkatesh** [comment]
Java 8 should be used. Java 9 or 10 will through Data Converter exception.
